version: '3.5'

services:
  postgres:
    container_name: 'passport_postgres'
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-passport}
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    restart: unless-stopped

  elastic:
    container_name: 'passport_elastic'
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elk:/usr/share/elasticsearch/data

  web:
    build: .
    restart: unless-stopped
    container_name: 'passport_django'
    ports:
      - '8000:8000'
    environment:
      PORT: ${PORT:-8000}
      SECRET_KEY: ${SECRET_KEY:-test_key}
    volumes:
      - ./passport/:/usr/src/app/
    depends_on:
      - postgres

  dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: unless-stopped
    container_name: 'passport_django_dev'
    ports:
      - '8001:8001'
    volumes:
      - ./passport/:/usr/src/app/
    depends_on:
      - postgres

volumes:
    postgres:
    elk:
