# Generated by Django 4.1.5 on 2023-01-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('article', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('document', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cities_light.city')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('accounted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('extra', models.BooleanField(default=False)),
                ('accounted', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.set')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='items',
            field=models.ManyToManyField(through='main.SetItem', to='main.item'),
        ),
        migrations.AddField(
            model_name='set',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.series'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_article', to='main.item'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.set')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.recipient'),
        ),
        migrations.AddField(
            model_name='order',
            name='sets',
            field=models.ManyToManyField(through='main.OrderItem', to='main.set'),
        ),
    ]
