# Generated by Django 4.1.8 on 2023-04-21 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="distributor",
            options={
                "verbose_name": "Distributor",
                "verbose_name_plural": "Distributors",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"verbose_name": "Recipient", "verbose_name_plural": "Recipients"},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name": "Series", "verbose_name_plural": "Series"},
        ),
        migrations.AlterModelOptions(
            name="set",
            options={"verbose_name": "Set", "verbose_name_plural": "Sets"},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="article",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="Article"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.models.item_img_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_set",
            field=models.BooleanField(default=False, verbose_name="Is set"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="series",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.series",
                verbose_name="Series",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="distributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.distributor",
                verbose_name="Distributor",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="document",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Document"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.recipient",
                verbose_name="Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sets",
            field=models.ManyToManyField(
                through="main.OrderSet", to="main.set", verbose_name="Sets"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="set",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="set_article",
                to="main.item",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="set",
            name="items",
            field=models.ManyToManyField(
                through="main.SetItem", to="main.item", verbose_name="Items"
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="serial",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="Serial"
            ),
        ),
        migrations.AlterField(
            model_name="setitem",
            name="amount",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Quantity should be >= 0."
                    )
                ],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="setitem",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="setitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.item",
                verbose_name="Item",
            ),
        ),
        migrations.AlterField(
            model_name="setitem",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.set",
                verbose_name="Set",
            ),
        ),
        migrations.AlterField(
            model_name="setitem",
            name="tray",
            field=models.IntegerField(
                default=1,
                help_text="Select tray 0 for optional items.",
                verbose_name="Tray",
            ),
        ),
    ]
